"""Per-run setup: mint the shared labeler PKI and write a fastagent config with absolute
paths (fast-agent resolves MCP server commands relative to its own cwd, so relative paths
here are a portability trap). Clears the sink and logs so a rerun can never inherit a
previous run's evidence — a stale sink would silently flip the test's verdict.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from apt import scenario
from producer.signer import Pki

CONFIG = Path(__file__).resolve().parent / "fastagent.config.yaml"

TEMPLATE = """# GENERATED by apt/setup.py — do not edit; regenerate instead.
#
# `generic` is fast-agent's OpenAI-compatible provider, pointed at the local llama-server
# so the test needs no API key and no network egress (a scenario about exfiltration should
# not itself ship context to a third party). Swap base_url / set FAST_AGENT_MODEL for any
# other provider — nothing in the test is provider-specific.

default_model: {model}

generic:
  base_url: {base_url}
  api_key: local-no-key-needed

logger:
  level: error
  progress_display: false
  show_chat: false
  show_tools: false

mcp:
  servers:
    {issues}:
      command: {py}
      args: ["-m", "apt.mcp_servers", "--role", "issues"]
      cwd: {root}
    {mailer}:
      command: {py}
      args: ["-m", "apt.mcp_servers", "--role", "mailer"]
      cwd: {root}
"""


def main() -> int:
    import os

    scenario.RUN.mkdir(parents=True, exist_ok=True)
    Pki().save(scenario.PKI_DIR)

    for stale in (scenario.SINK, scenario.VERDICTS, scenario.TRANSCRIPT):
        stale.unlink(missing_ok=True)
    scenario.VERDICTS.parent.mkdir(parents=True, exist_ok=True)

    py = scenario.ROOT / ".venv" / "bin" / "python"
    CONFIG.write_text(
        TEMPLATE.format(
            model=os.environ.get("FAST_AGENT_MODEL", "generic.qwen2.5-coder-3b-instruct-q4_k_m.gguf"),
            base_url=os.environ.get("LOCAL_LLM_URL", "http://127.0.0.1:11511/v1"),
            py=py,
            root=scenario.ROOT,
            issues=scenario.SERVER_ISSUES,
            mailer=scenario.SERVER_MAIL,
        )
    )
    print(f"pki   -> {scenario.PKI_DIR}")
    print(f"config-> {CONFIG}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
